[package]
name = "ch8ppy"
version = "0.1.0"
authors = ["Olivia Palmu <oliviaspalmu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "^0.19"
rand = "^0.8"
argh = "^0.1"
